### ISSUE TITLE
quest=11878

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#1]
Khu'nok Will Know

Calf runs much faster than he has to

Dude got to slow down

https://www.youtube.com/watch?v=2Y2PQDhZ8NI

By completing quest

**Comment by YggdrasilWotLK** [comment]
Thanks for your report. We've looked into this issue and see that the calf's movement speed is set to that of pets/companions, which are linked to the player's current speed through core functionality. Sadly, we can't rewrite the pet movement system to allow for this to move more naturally. We'll have to consider this one merely a cosmetic glitch :)
