### ISSUE TITLE
The Headless Horseman jitters through the air

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#103]
He should not jitter through the air. Seems the c++ script in hallows_end.cpp is erroneously configured as it never actually disables his gravity. Plus, his waypoint_data script (236820) is FAR too high up in the air. Things I've tried:

1. Disabling gravity as a timed event after spawn using ELUNA hooking on to him through the pumpkin. Didn't work, he kept jittering unless I mixed a hover start and gravity disable ever 20ms for 17 seconds. Obviously a terrible solution.
2. Using creature_template_movement to lock in both flight states "disable gravity" and "can fly", then disable later. Didn't work, he started flying permanently.
3. Hooking onto packets for gravity spline movement. None present, unless toggling off and on with approach no. 1, very rapidly, which again is a terrible approach.
4. Enabling hover through creature_template and setting hover height to between 20 and 40 yards. Didn't work at all, this just got him stick mid air. 
5. Correcting the waypoint_data Z to match a more Blizzlike path. He doesn't listen and defaults to around Z = 32 as this is the invisible "floor" in the zone that he falls to because he can't fly.
6. Making his movetype in waypoint_data be "fly". Doesn't seem to do anything.

@Lortz92 any ideas? Give up and c++ it so that it'll be correct next year at least? Or do you have any tricks up your sleeve?

**Comment by Lortz92** [comment]
No unluckily i have no clue to how to solve this without c++ .  Tried something DB side but was completely uneffective with the script c++ running

**Comment by YggdrasilWotLK** [comment]
The c++ script doesn't actually control his movement flags, it just starts his wp movement. But at every wp reached, his movement flags are reset...

**Comment by YggdrasilWotLK** [comment]
Fixed his movementinform to apply flight on spawn, refresh on each waypoint and remove on finalized path

```
    void MovementInform(uint32 type, uint32 point) override
    {
        if (type == WAYPOINT_MOTION_TYPE)
        {
            if (point == 0)
            {
                me->CastSpell(me, SPELL_HEAD_VISUAL, true);
                me->SetCanFly(true);
                me->SetDisableGravity(true);
            }
            else if (point > 0 && point < 11)
            {
                me->SetCanFly(true);
                me->SetDisableGravity(true);
            }
            else if (point == 11)
            {
                me->ReplaceAllUnitFlags(UNIT_FLAG_NONE);
                me->StopMoving();
                me->SetCanFly(false);
                me->SetDisableGravity(false);

                me->SetInCombatWithZone();
                inFight = true;
                events.ScheduleEvent(EVENT_HORSEMAN_FOLLOW, 500ms);
                events.ScheduleEvent(EVENT_HORSEMAN_CLEAVE, 7s);
            }
        }
    }```
