### ISSUE TITLE
Quest: Lightning Infused Relics

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#108]
**Title:** Lightning Infused Relics (11494)
https://www.wowhead.com/wotlk/quest=11494/lightning-infused-relics

**Issue:** Bluff ability of controlled robot is barely working, making the npc's aggro you and you can't fight back, so player has to get new robot every time he gets "caught". More than doubles quest time.

**Intended functionality:** The player inside a robot is disguised as one of the enemies as they wander through the enemy outpost. Once in a while the enemy talks to the player, confronting their disguise. The player should be able to "bluff" the enemy (button number 3), to keep away any suspicion. If they fail to react and bluff the enemy, they will aggro the player.
Note: "Bluff" also doesn't work properly in previous quest (Iron Rune Constructs and You: The Bluff - 11491) but it doesn't matter than much there because we can just spam the bluff until it eventually works.

**Reproduction steps:** Just take the quest, and go to the quest location and try to bluff any enemies that confront you.

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/b73760b6-7d7d-478f-99f9-9ed60be85282)
![image](https://github.com/user-attachments/assets/ce2f2f56-8be9-4a2b-9d67-3dc5ceeca35a)
![image](https://github.com/user-attachments/assets/b2eb27d6-09bb-4cd6-b773-15e49cea70b8)


insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('24825','0','15','0','31','0','100','512','44609','0','0','0','0','0','75','44643','0','0','0','0','0','23','0','0','0','0','0','0','0','0','Iron Rune Construct - On spell 44609 hit target - Add aura 44643 to owner');

It's a hack but it works
