### ISSUE TITLE
Bad NPC state: Surveyor Orlond

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#109]
**Title:** Bad NPC state: Surveyor Orlond
https://www.wowhead.com/wotlk/npc=26514/surveyor-orlond

**Issue:** Surveyor Orlond should be dead, but he is very much standing, while being labeled "dead"

**Intended functionality:** He should be dead lying on the ground

**Proof:** 
![WoWScrnShot_101924_010735](https://github.com/user-attachments/assets/8cdbb861-f899-47da-b084-dacd0d802d1a)

**Comment by YggdrasilWotLK** [comment]
INSERT INTO creature_template_addon (entry, path_id, mount, bytes1, bytes2, emote, visibilityDistanceType, auras)
VALUES 
(26514, 0, 0, 0, 1, 0, 0, "58806 61204");

![image](https://github.com/user-attachments/assets/ee82763e-ba00-41f1-8161-5fb2092c8ccb)
