### ISSUE TITLE
Quest
Conversing with the Depths (ID: 12032)
The point of the quest should be to click a magic crystal ball to summon "Sea-Goddess Oacha'noa", and follow her instruct to jump into the depths in front of her. During the fall the quest should be marked as complete.
Instead the quest is **automatically** marked and complete, sending player to quest receiver "Toalu'u the Mystic", who won't take the quest in, because it hasn't been done for that npc. Making the quest unachievable

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#11]
Quest
Conversing with the Depths (ID: 12032)
The point of the quest should be to click a magic crystal ball to summon "Sea-Goddess Oacha'noa", and follow her instruct to jump into the depths in front of her. During the fall the quest should be marked as complete.
Instead the quest is **automatically** marked and complete, sending player to quest receiver "Toalu'u the Mystic", who won't take the quest in, because it hasn't been done for that npc. Making the quest unachievable

**Comment by Lortz92** [comment]
I actually checked that the quest is marked as autocomplete but you can still turn on toalu after the summon of Oacha'noa and complete it.

**Comment by YggdrasilWotLK** [comment]
@lortz92 so no change neded?

**Comment by Lortz92** [comment]
Well i think can be improved but with lots of work because many area triggers are missing from the point you jump to credit you the quest or not. After the jump it autocompletes but then you can still turn in the quest completed to toalu even it isn't showed on minimap. But maybe testers can check that if it's ok with them.

**Comment by YggdrasilWotLK** [comment]
@Lortz92 I'm feeling adventurous enough to unclunk this one. Can you remove the autocomplete from the DB on QA?

**Comment by YggdrasilWotLK** [comment]
Fully ELUNA-d, detached from CPP and smart_scripts, added all emotes (33 on speech, 374 on submerge) and sounds (11558 on speech, 11561 on submerge), added proper tracking of player Z, recreated both the completion and failure events, and corrected auras (compulsion = 47098, quest complete swim speed = 41273)  and fixed timings. Should be perfectly OK now.

Script: https://github.com/YggdrasilWotLK/ELUNA-Scripts/blob/main/Quest/12032.lua

Source: https://www.youtube.com/watch?v=9UvmWrS-3B8
