### ISSUE TITLE
Teleporter not working Zul'Drak

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#110]
**Title:** Unfunctional teleporter

**Issue:** During the quest Sabotage the player is asked to learn Drakuru's secret by taking a tour guide on upper level of Voltarus, however after the tour finishes, the player is unable to use the teleporter to get down, leaving them stuck on the upper level.
https://www.wowhead.com/wotlk/quest=12676/sabotage

**Intended functionality:** The teleport should port you down

**Proof:** 
![WoWScrnShot_102224_222210](https://github.com/user-attachments/assets/df6d4ed4-265c-4a8b-9f2c-5e725fb146f4)

**Reproduction steps:** Didn't try it out of quest, but taking teleporter to upper level of Voltarus should be enough. Then try to use the teleporter again to go down.

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/fd98d55c-c505-4568-86ff-668fce64d7f4)

```
DELETE FROM conditions
WHERE SourceTypeOrReferenceId = 22
  AND SourceGroup = 1
  AND SourceEntry = 5080
  AND SourceId = 2
  AND ConditionValue1 = 52678;
  
DELETE FROM smart_scripts
WHERE entryorguid = 5080
  AND source_type = 2;

DELETE FROM areatrigger_scripts
WHERE entry = 5080;
