### ISSUE TITLE
Quest: Scalps! (12659)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#111]
**Title:** Quest: Scalps! (12659)
https://www.wowhead.com/wotlk/quest=12659/scalps

**Issue:** The player is asked to scalp 10 Heb'Drakkar trolls. However the player can only strike the trolls on foot (Heb'Drakkar Headhunter), but cannot scalp the trolls riding a bat (Heb'Drakkar Striker)
https://www.wowhead.com/wotlk/npc=28465/hebdrakkar-striker
https://www.wowhead.com/wotlk/npc=28600/hebdrakkar-headhunter

**Intended functionality:** The player should be able to scalp both versions of the trolls

**Proof:** 
![WoWScrnShot_102324_004222](https://github.com/user-attachments/assets/d188db5b-4b8c-4698-ac48-fea14a9a85bf)

**Comment by YggdrasilWotLK** [comment]
local function OnUseItem(event, player, item, target)
   if not player:GetSelection() then return false end
   local sel = player:GetSelection()
   if (sel:GetEntry() == 28465 or sel:GetEntry() == 28600) and sel:IsDead() then return true end
   return false
end

RegisterItemEvent(38731, 2, OnUseItem)

WorldDBExecute("UPDATE `conditions` SET `ConditionValue2` = 0 WHERE `ConditionValue2` = 28600 AND `SourceEntry` = 52090 AND `SourceTypeOrReferenceId` = 17;")

![image](https://github.com/user-attachments/assets/3a0984ae-6b74-4794-bbe4-6906b95c1fc9)
