### ISSUE TITLE
Quest: Convocation at Zol'Heb

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#112]
**Title:** Convocation at Zol'Heb
https://www.wowhead.com/wotlk/quest=12730/convocation-at-zolheb

**Issue:** The player gets into a fight with prophet of Akali. When the prophet gets to 75% hp, he stuns the player and keeps them like that. Eventually losing aggro and leaving combat.

**Intended functionality:** When the prophet reaches 75%, he stuns the player, but should begin a small "role playing" dialogue, after which the cat goddess Har'koa should help the player. This dialog never triggers, leaving the player in long stun.
https://youtu.be/97j-wwK_soU

**Proof:** 
![WoWScrnShot_102324_232836](https://github.com/user-attachments/assets/940ac004-6efa-4ff5-b068-49aea6e83f17)

**Comment by YggdrasilWotLK** [comment]
Closing to follow up in original issue (https://github.com/YggdrasilWotLK/Yggdrasil-WoW/issues/51), will find whatever is still gunking this up there
