### ISSUE TITLE
() In Icecrown after accepting the Quest "The Will of the Naaru" there should be start a minievent theres a portal spwan to Shattrath, but the event dnt start and theres no portal.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#113]
In Icecrown after accepting the Quest "The Will of the Naaru" there should be start a minievent theres a portal spwan to Shattrath, but the event dnt start and theres no portal.

**Comment by Ye-Old-Potato** [comment]
Yes, this is correct, this event does not occur on prod - Please observe the attached video for what it should look like, simple script needs to be added onto an NPC who is present, but doesn't move around in our case. The actual event itself, is very self explanatory and quite straightforward, its a very short 10 second role-paly of a mage npc casting a portal with 1-2 dialogues iirc.

https://www.youtube.com/watch?v=ALeZWZCKJb4&ab_channel=WorldOfWarcraftGuidesAndGameplay

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/b85e0372-dc32-47ad-89dc-2118ead70cc7)
Added
