### ISSUE TITLE
Quest: The Scryer's Scryer (ID: 11490)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#116]
Quest: The Scryer's Scryer (ID: 11490)

There's a ball inside Magister's Terrace - the titular Scryer's orb or w/e its called. This object is the quest item that needs to be used, upon it being used an animation triggers the flying in and landing animation of the npc. Then you can turn in the quest.

In our case he is perma-spawned and the problem is that upon using the orb, it does not register it's "use" as it doesn't "spawn" the npc into the spot where he should be as in the video below.

Note: Some servers from the case history have struggled with this bug, and in some cases, certain types of fixes such as Warmane's set and "Feenixproject" or w/e its called on git, seem to have had issues that cause multiple uses of the orb by a dungeon team to cause multiple instances of the npc spawning.

This is a tbc piece so I am surprised that Chromie and their squad haven't fixed this thing, regardless, there's provided below a video which I am not 100% sure if its from wrath, but the chain of events I am confident is 100% blizz like as it used to be back in the day in tbc at least.

https://www.youtube.com/watch?v=IqwF-KwnjVo&ab_channel=TheChroniclesofAzeroth

**Comment by Ye-Old-Potato** [comment]
Addendum: This seems to work perfectly if its the first time - I think it starts randomly bugging out second time or so, or if many people do it, or if you do it once and cancel it, then watch it through. There seems to be a timer to the whole event, which is confusing to actually figure or understand for most players. So like there's a way to make it happen and work normally, but only if you know exactly how the whole thing works.

**Comment by YggdrasilWotLK** [comment]
Is it supposed to be completable more than once per instance @Ye-Old-Potato ?

**Comment by Ye-Old-Potato** [comment]
Well no, Technically it is not supposed to be completable more than once per instance though iirc in some expansions and versions I am aware of it becoming a case where it works in the same fashion as the Pit of Saron quest. 

That said, while technically I cannot find any evidence to suggest that it can or cannot be completed more than once, I think, if it is possible, I would recommend that we create a quality of life factor here that just "group completes" the quest in the same fashion as Pit of saron slaves quest or so simply because of the nature of what this quest provides it only makes sense.

**Comment by YggdrasilWotLK** [comment]
The quest works fine for me on two accounts if the players use the orb roughly at the same time. 

Think the issue you're seeing is from Kalecgos casting the complete credit spell once he finishes his waypoint, so if you do it more than about 58 seconds apart during the same instance lockout, it won't complete. Could also be range limited, not sure. 

I've made it complete 10 sec after use now for simplicity. All players that want to complete the quest will still need to use the object themselves.
