### ISSUE TITLE
How To Slay Your Dragon (13003)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#118]
**Title:** How To Slay Your Dragon (13003)
https://www.wowhead.com/wotlk/quest=13003/how-to-slay-your-dragon#comments

**Issue:** During the quest the player is tasked to slay a dragon and is given new set of skills to do so. One of them being "Dodge", after which the player cannot be attacked by the dragon. However there is NO visual warning about the dragon trying to reach the player, therefore it's a guessing game if the players can time it correctly.

**Intended functionality:** The player should be shown a visual warning on the screen ~2 seconds before the dragon swipes the player so they have chance to dodge.

https://youtu.be/wrbIzLUlQSw
It should look something like this

**Reproduction steps:** Just pick up the daily from sons of hodir

**Comment by YggdrasilWotLK** [comment]
@Lortz92 possibly smart scripted? If so we should add an area trigger message 2 sec before the swipes

**Comment by Lortz92** [comment]
Unluckily it isn't smart scripted but cpp. Script is zone_storm_peaks.cpp responsible for this NPC. Don't know what isn't working from the code, for what i've seen seems good but obviously there's something  not working, maybe we should do a report on azerothcore about this

**Comment by YggdrasilWotLK** [comment]
Replaced the Talk(X) with 
 
                        player->GetSession()->SendAreaTriggerMessage(...);

**Comment by YggdrasilWotLK** [comment]
Seems the dodge spell script didn't work either so I rescripted it. It's mostly OK now. There's some odd evades that occur every now and then seemingly without any explicit cause; did you notice anything like that when doing this quest @JaRy66 ? Edit: I probably lost my grip lol

![image](https://github.com/user-attachments/assets/991bdfd9-3104-42fc-a9c9-3f582ba6c0e0)
