### ISSUE TITLE
Invisible wall in Storm Peaks

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#119]
**Title:** Invisible wall in Storm Peaks in Terrace of The Makers

**Issue:** At around 39;40 in storm peaks there is a invisible wall quite far away from the pillar itself. Not sure if it can be fixed, however you might want to try and change the position of one of the NPC's, which seems to be stuck inside of that wall

**Proof:** 
![WoWScrnShot_102824_233929](https://github.com/user-attachments/assets/0de17f0d-b2e8-46f0-8125-af8125949867)
![WoWScrnShot_102824_233932](https://github.com/user-attachments/assets/1bfcf324-5235-494b-a173-dc4255660e11)

**Comment by YggdrasilWotLK** [comment]
So these invisible walls are actually client-side collision, we can't control them. But we can control the NPC and we've moved it to an appropriate position now
