### ISSUE TITLE
These boats near Kaskala in Borean Tundra seem to be stuck, they should be patroling around and moving

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#12]
These boats near Kaskala in Borean Tundra seem to be stuck, they should be patroling around and moving

**Comment by Ye-Old-Potato** [comment]
This issue can be confirmed to be occurring - they seem to be static. The npc's are performing the rowing action of the boat but are not moving it an inch. (69.2, 62.6) <-- These coordinates are the best spot to observe an exhibit of this issue upon 2 examples.

**Comment by YggdrasilWotLK** [comment]
Pathing added, landing event not added yet but will handle that as separate issue in the future
