### ISSUE TITLE
Quest: Messenger to the Feralfen (ID: 9803)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#122]
Quest: Messenger to the Feralfen (ID: 9803)

You should be able to drink the quest item, waltz in and chat with the guy then finish the conversation and this should complete the quest. However, the process is doable but the completion trigger does not occur, in that, the quest does not "complete" upon performing all the required steps to do so.

**Comment by YggdrasilWotLK** [comment]
Completes just fine for me. Got any more details to share?

![image](https://github.com/user-attachments/assets/f96484e7-9b7e-4d5b-bd07-8e13fc7e41d8)

**Comment by Ye-Old-Potato** [comment]
That makes no sense, I completed the dialogue multiple times on 2 characters to no avail, reloged, cache wiped and so on as well, there's nothing beyond that that could have interfered with the quest completion either. I have not tried this on QA though, I only did on the live.

**Comment by YggdrasilWotLK** [comment]
FYI your local cache can't influence quest completion.

I'm testing this live too.

So what completes the quest is receiving an item, not clicking through the dialogues per se. Are your bags full for example?

Edit: The item spawns from spell ID 32152 being cast on you. If you are for some reason untargetable by the NPC/spell I imagine it can make it impossible to get  the item too. You could always test by just doing ".cast 32152" on yourself, it should replicate what the finishing dialogue does

**Comment by Ye-Old-Potato** [comment]
Nope, bags had a good bit of space and also the final attempt when I tried seemed to have the dialogue box gone entirely today as well when I was trying it out again on a second toon. I had the quest, and had used the item per the instructions but nothing seemed to happen.

The spell ID I can try casting on myself to make it complete but I am not sure why that would not be happening when doing the quest normally.

Update: Ignore the dialogue box issue, that was an error on my part. I didn't have the correct quest added.

**Comment by YggdrasilWotLK** [comment]
What do you mean by the dialogue box being gone? Do you have any screenshots?

**Comment by Ye-Old-Potato** [comment]
I'll re-run this a few more times on the qa if needed but I'm not sure what exactly the point of failure might be, it normally should be that go through the full conversation in the dialogue boxes and that should cause the quest to become completed. 

As of yet, I have only managed to get it to successfully complete 1 out of 3 times on live server by doing it the normal way without the use of any commands.

**Comment by YggdrasilWotLK** [comment]
I've done it successfully five times so far so whatever issue you had, I
can't replicate it. Will need more information if we're going to change
anything here so yes please re-run. It's fine to rerun it on prod

**Comment by Ye-Old-Potato** [comment]
Alright, I'll investigate it and try to see what might be causing it.

**Comment by Ye-Old-Potato** [comment]
I think I have narrowed this down to exactly how this happens and I think I might know where the problems came from - Like you mentioned earlier there's a chance I had bag space but that was in a profession bag rather than standard issue bag and that might've caused problems. Since after trying millions of permutations and combinations of random ways to fail the thing, that's the only reliable way to actually cause the quest to fail. 

That said - I think it might be best suited to leave this one aside for the time being given the above, until such time as more players face this issue and bring up further reason or means to break said quest. I think for the time being, it appears like a me problem lol.

So yes, if you see it appropriate, I think it best we archive this away for the time being. You may do so, or I can as well if you see it fit.

**Comment by YggdrasilWotLK** [comment]
OK closing
