### ISSUE TITLE
() Quest: "A Race Against Time" couldnt attack the mobs except through aoe, 
You can set off the bomb but the inquisitor and hunters can't be targeted, however they can be killed using aoe attacks like hurricane, death and decay, maybe consecration

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#123]
Quest: "A Race Against Time" couldnt attack the mobs except through aoe, 
You can set off the bomb but the inquisitor and hunters can't be targeted, however they can be killed using aoe attacks like hurricane, death and decay, maybe consecration

**Comment by Ye-Old-Potato** [comment]
This is a strange one - You can easily attack them, however the caveat is that you need to move around and plant your bombs on each of the cubes and actually give it a couple moments to for the explosions to occur, its hard to miss once they do occur and its only a few 4-5 seconds of wait at most. Once this happens, they are fully targetable and attackable without the need to rely on aoe or anything - I auto attack killed one for instance, obliterate, shadowbolts, firebolts, they all work just fine provided you give them the time to land first and obviously use the bombs from inside the force field exactly as mentioned in the quest description so it seems to function fully in line with Blizz functioning. 

I am unable to replicate any such issue as of now, so if there is one this will require further investigation and more precise instructions on exactly how they managed to break it.

**Comment by YggdrasilWotLK** [comment]
Ten minutes after the original report, the player appended this:
```
OK weird it works but I first killed the hunters then set off the bomb and then defeated inquisitor 
I will try setting off the bomb before I attack anything
```

Then he didn't try again. Might be a false positive

**Comment by YggdrasilWotLK** [comment]
There's no scripting attached to the mage hunters, nothing can affect their attackability flag. They're just set to always attackable and aggro on range. As for the inquisitor, just gotta throw enough bombs. False positive, closing
