### ISSUE TITLE
(Quest) Judgement Day Comes shouldn't be available if the Argent Vanguard questline has been started

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#124]
https://www.youtube.com/watch?v=dc5sBGfz3kE

**Comment by Ye-Old-Potato** [comment]
Quest issue: Judgement day comes!

![Screenshot_2024-11-10_104757](https://github.com/user-attachments/assets/43ff6db3-4f96-4c0e-993c-85307b339dea)
![WoWScrnShot_111024_103838](https://github.com/user-attachments/assets/1e22b000-69f6-4463-b2a6-6ead024d0cf7)

There exists a very strange set of issues observed on this quest. 
1. There seem to be some intersecting quests that cause phasing issues here.
2. There is an unknown quest that seems to cause this specific quest to cause the 2 required NPCs to become phased out. (My theory is it is the breadcrumbs quest mentioned in here - https://github.com/TrinityCore/TrinityCore/issues/10644)
3. The prior mention is a trinity core issue, however, I have observed a very similar problem occurring on our own AC server too, hence I've only posted it for a point of reference.
4. Finally, a bunch of wowhead comments that specifically mention this quest and speak of issues that seem to have existed on blizz as well at some point that might be worth notice - https://www.wowhead.com/quest=13226/judgment-day-comes#comments

Please let me know if any further investigation is required herein - Screenshots posted show the 2 missing npcs, and a second with them present as posted by the player.

Addendum: There are certain circumstances if you have engaged with no other Argent quests and only started with this specific questline without deviation in which case it remains completable per normal, however, within reason this feels like not something normal players without express awareness of this issue would know of and work around.

**Comment by YggdrasilWotLK** [comment]
This quest shouldn't be acceptable if players have already started the Argent Vanguard questline. Should just be abandoned if players already have. Not really a major issue

**Comment by YggdrasilWotLK** [comment]
Fixed
```
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(19, 0, 13226, 0, 0, 47, 0, 13036, 1, 0, 0, 0, 0, '', 'Quest 13226 only available if 13036 is not taken'),
(19, 0, 13227, 0, 0, 47, 0, 13036, 1, 0, 0, 0, 0, '', 'Quest 13227 only available if 13036 is not taken');
