### ISSUE TITLE
Core Mechanics issue: Demon Warlocks spells are not castable in Metamorposis.

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#125]
Demon Warlocks spells are not castable in Metamorposis.

A demon warlock cannot cast most spells in the Demon form for unknown reasons - This issue is under investigation currently as observed on 2 players' warlocks.

Observe the video provided below for the issue demonstrated.

https://github.com/user-attachments/assets/85b8bacc-53fd-47e4-8077-48c39717de05

Intended functionality: The demon form either should not be classed as a "shapeshift" or at the very least, spells such as those should be usable in such a form. Below is a video that evidences the casting of normal rotation spells within the demon form in wrath expansion.

https://www.youtube.com/watch?v=I8gQpRzf8Rc&ab_channel=AKA

This issue is currently being further investigated.

**Comment by YggdrasilWotLK** [comment]
Not a core mechanics issue, just a spell mishap. Fixed yesterday
