### ISSUE TITLE
Quest: Delivering the message (ID: 10406)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#132]
This quest is supposed to, upon acceptance, spawn an npc that kinda does the quest objective while you protect him. 

Problem: Said npc does not spawn - Note the video below. Unsure why it happens.

Intended behavior: Observe the following, second, YT link.

https://github.com/user-attachments/assets/b9abde88-0c44-416e-aaca-0a37e25c92d3

https://www.youtube.com/watch?v=JH5nXTkvH-o&ab_channel=MichaS

Addendum: There's also a slight phasing issue that seems to occur between quests, where the giver of the quest seems to vanish out of phase, and the platform that spawns him also vanishes so you cannot spawn him as you normally would, that does reset itself if you just wait for 2-3 minutes but that doesn't seem intended, though I cannot say for sure what or why this is happening - Upon using a GM toon, I can interact with said phased object by using gm mode and cause the quest giving npc to appear again, but there is some funny stuff happening. Note below the screenshot for reference on this.

Before:
![image](https://github.com/user-attachments/assets/34c6a2ab-12e0-48d7-a259-e3097152c45c)
After the 2 mins of wait time:
![image](https://github.com/user-attachments/assets/0a343904-c137-41a1-9e63-db35cd644fd3)

**Comment by YggdrasilWotLK** [comment]
What are the relevant NPC IDs and how do we start this quest event using GM commands?

**Comment by Ye-Old-Potato** [comment]
![image](https://github.com/user-attachments/assets/ceca1678-74c4-4a06-bc86-47d0dbccd4b0)

![image](https://github.com/user-attachments/assets/2269ab95-50b6-48d2-9f4c-8f291756c39f)

Position and script, I have no idea what a GM command is to start the event but you can simply go GM mode and interact with his platform to spawn him and "start the event" as such. Since without quest you may not see the platform due to phasing issues.

**Comment by YggdrasilWotLK** [comment]
The smart script to cast the spell that summons the escort NPC fails sometimes so I've added an ELUNA failsafe to ensure it always spawns as intended.

What you're seeing with the platform to spawn the quest giver isn't a phase issue, it's just that after use, it turns inactive and despawns for a few minutes before respawning later. In GM mode, you can see all creatures regardless of both phase and spawn state, meaning you can both see and interact with despawned creatures when it's on. The platform returns to normal after a short while. Not sure if it's supposed to despawn or not but it works
