### ISSUE TITLE
NPC Looking funny

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#138]
There's a bunch of Marksmen at the Isle of Quel Danas which simply do not have bodies - Only weapons floating in the air like phantoms. Screenshot attached below.

![image](https://github.com/user-attachments/assets/d3ebc7af-5ac4-4d86-aef2-76ea2148e0d7)

**Comment by YggdrasilWotLK** [comment]
Re-imported (inaccurate) models but so be it, it looks fine. Syncs with next restart
