### ISSUE TITLE
Quest: Fel and the Furious (10612)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#139]
Quest: Fel and the Furious (10612)

You take control of a reaver and missile some infernals to death - This is fairly simple and straightforward but the quest has a timer and the actual reaver should be allowed walk all the way to the edge of the platform area as shown in the YouTube video - However, this is not the case, as demonstrated in the recording from live In-game footage.

This would be doable without being able to walk to the edge, however, the timer makes the quest nigh impossible.

Current status:
https://github.com/user-attachments/assets/d3c38c80-c178-41f1-8f68-4936b6e341a8

YouTube link to what it should be like:
https://www.youtube.com/watch?v=cfZN1pCH9Ck&ab_channel=TheChroniclesofAzeroth

**Comment by YggdrasilWotLK** [comment]
I don't understand what the issue is, something is cancelling the channel?

**Comment by Ye-Old-Potato** [comment]
Unsure, I think there's possibly a range issue to the channel. My guess is its a zoning problem, like the zonal boundary is what cancels the channel normally, but in this case, somehow it is smaller than the entire rectangle staging area - Which is the original, intended area wherein this boundary is supposed to be as per that video.

**Comment by YggdrasilWotLK** [comment]
Think the issue is the visibilityDistanceType (https://www.azerothcore.org/wiki/creature_addon#visibilityDistanceType) derendering the NPC as it steps over 100 yards away from the player, causing the channel to break as it can no longer find its target

**Comment by Ye-Old-Potato** [comment]
I don't imagine this is because of graphics settings being at the lowest, would it? 

Regardless of which, the workaround options we can add in, if such a thing becomes needed to do, are one of the 2 options

1. Reduce the respawn timer to <10 seconds so that its possible to re-kill enough of them within the quest timer.
2. Simply remove said quest timer and allow re-killing and just let the player camp the place for some 10 minutes.

**Comment by YggdrasilWotLK** [comment]
No this isn't related to your graphics settings. 

I set the NPC visibility to some 400-500 yds now and I'm now permitted to walk a few more steps but the channel breaks regardless. Seems spell 38003 has some kind of fault. The NPC also doesn't evade when the channel breaks. The smart script for entry 21949, on aggro - evade, is broken so I'll change that for an ELUNA script instead.

As for changing the kill targets' respawn time or quest timer, I'm much more intent on instead fixing the underlying issue than finding a multitude of workarounds

**Comment by Ye-Old-Potato** [comment]
Ah alright, fair. Yes, of course.

**Comment by YggdrasilWotLK** [comment]
https://github.com/YggdrasilWotLK/yggdrasilcore/commit/2711bd11a0f9a1f82bcb9e06394d1f92e641f92a
