### ISSUE TITLE
(quest) For the Midsummer event, the More Torch Tossing and also I believe More Torch Catching daily quests don't appear to be rewarding the exp they say they should. Did More Torch Tossing on several toons in different cities and got no exp.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#15]
For the Midsummer event, the More Torch Tossing and also I believe More Torch Catching daily quests don't appear to be rewarding the exp they say they should. Did More Torch Tossing on several toons in different cities and got no exp.

**Comment by YggdrasilWotLK** [comment]
Seems to be related to requests of dailies not giving XP overall

**Comment by Ye-Old-Potato** [comment]
Can't say - these quests upon trying do seem to provide the exact experience mentioned within the quest descriptions which remain dynamic over levels. Therefore it cannot conclusively be said if this is the case.

**Comment by YggdrasilWotLK** [comment]
This is probably just a tooltip issue re https://eu.forums.blizzard.com/en/wow/t/repeatable-quests-for-exp-in-tbc/273281

**Comment by YggdrasilWotLK** [comment]
Will handle in general repeatable quest tooltip issue here https://github.com/YggdrasilWotLK/Yggdrasil-WoW/issues/23
