### ISSUE TITLE
(quest,quest,quest) Above is one example of a general problem that occurs occasionally. I quest is complete and indicated on the minimap and quest log, but the quest giver does not have the ? over his head. Low-priority issue, but I have seen it throughout the game.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#20]
Above is one example of a general problem that occurs occasionally. I quest is complete and indicated on the minimap and quest log, but the quest giver does not have the ? over his head. Low-priority issue, but I have seen it throughout the game.

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/104b5eb7-eae8-4c4a-944f-4c8b99912bda)

**Comment by Ye-Old-Potato** [comment]
This, upon testing on nearly 100 quests on live and dev end, seems to not be repeatable - However, this issue does pop up when using Carbonite and can be fixed through settings alteration. I would assume, that this is the resolution here as well and is likely not a bug from the server end but rather only a settings issue.
