### ISSUE TITLE
On Ruby Wings

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#24]
quest=12498

Dragon's don't want to chomp scavengers to regenerate (ability on key 3 doesn;t work as intended on melee range). I could understand them, I wouldn't want to eat rotten meat too, but still you gotta do what queen momma tells you to do, no rotten ghoul eating - no tasty blue dragonflight for dessert.

Dragons are supposed to eat ghouls. Icky! 

Also, while on quest, I fell through textures while under fear from Antiok twice, but have no proof of that nor recorded witness of same events from others.

https://www.youtube.com/watch?v=Lj1BcMuBfWY 00:25 shows how ability should work.

**Comment by YggdrasilWotLK** [comment]
In what area were you feared? We can add a failsafe there. Is the ghoul eating spell quest-breaking or can we add it to the to-do list for later?

**Comment by SamoyedProtW** [comment]
> In what area were you feared? We can add a failsafe there. Is the ghoul eating spell quest-breaking or can we add it to the to-do list for later?

In area of fighting Antiok, his hill, his ability sets 10 seconds fear effect during which if you run to the edge of the hill, game wants you not to fall, but makes you run through textures of the hill trying to get you back up and you fall through and die. Ghoul eating is not essentially required, but whenever drake runs out of energy - he drops you off and you may die, though newly spawned drake will have full energy

**Comment by YggdrasilWotLK** [comment]
Chomp issue verified, on second ghoul eating, the ghoul replaces the player as the rider of the mount and player gets dropped. Needs to be rescripted to not count 2nd ghoul as mounter

**Comment by YggdrasilWotLK** [comment]
Fixed, ready to test

**Comment by Ye-Old-Potato** [comment]
This is done now, fully functional as intended blizzard functionality and ready to send live.
