### ISSUE TITLE
Quest: Spiritual Insight

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#26]
During the quest the player has to use a "powder" to gain spiritual insight and fly around selected areas of dragonblight. While the quest does work, player is supposed to "transform" into some sort of whisp while the flying phase is happening. Instead the player only turns invisible while their weapons are still visible.

How it should look: https://youtu.be/6cCbmLz9Xeg
![WoWScrnShot_062924_005914](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/778f75fe-20dc-4177-99e6-a736cccf0d40)

How it looks now should be visible in the picure I added in this Issue (Considering it actually works)

**Comment by YggdrasilWotLK** [comment]
Fixed

![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/3e9a85ba-f6e2-4a7f-a2b4-231ee4414024)
