### ISSUE TITLE
Emergency protocol: Section 8.2, Paragraph D (minor visual issue)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#27]
Quest is working as inteded, no issue with quest functionality, however one of the Scuttle wreck you're supposed to burn has it's fire animation off the actual scuttle wreck. Specifically the one at 60,33 (Borean Tundra)

Please move the fire by a bit so the actuall scuttle is now under fire, and not the water.
![WoWScrnShot_070224_163719](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/8cbb522c-237a-4191-8952-174b850ac24c)

**Comment by YggdrasilWotLK** [comment]
Moved ![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/fc685d1c-8cf6-4ae7-b19b-5702344e99a0)
