### ISSUE TITLE
Overly agressive flying mount dismounting (Funcionality)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#28]
While running with flying mount over watery surface, it auto dismounts player, however if the player is using a mount that cannot fly, the player can keep freely running.

https://youtu.be/u7S5tA1Rahc

I'm guessing there is auto dismount at ceratin point when the player is in the water, as players cannot mount flying mounts while swimming. But this point of dismount is way too soon, making it annoying to use.

The goal of this would be that players can run with flying mounts over such surface. (While this is useless for players in most cases, it affects also mounting up in these types of water, because if the player doesnt immediately fly up, it kicks them off the mount) I tested this in Borean tundra, in lakes south of Fizzcrank's Airstrip

**Comment by YggdrasilWotLK** [comment]
I think I've found the culprit and added a failsafe to adjust for elevation gap between shallow water and swimming state. In progress but will need further testing to ensure there's no unfortunate side effects

![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/89352ce5-fdd1-41b3-b6b6-618704c70f5a)

**Comment by YggdrasilWotLK** [comment]
We've told the game to stop throwing people off mounts unless they're underwater. Now it lets me safely land on shores like this one and step onto land without getting yeeted

![image](https://github.com/user-attachments/assets/43b1a1ac-ca96-47c6-8760-bab6c303a719)
