### ISSUE TITLE
(NPC) Alive NPC should be dead

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#29]
There's alliance soldier out of place at ~65,65 in Icecrown.

You cannot click on him, interact with him, he just sits there.

Please return him home

![WoWScrnShot_070824_000634](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/343e60d3-0305-466e-8a29-7ab8028584e3)

**Comment by YggdrasilWotLK** [comment]
Where is his home?

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/2a44d8c7-d29e-4f81-abc6-401c921a1dd5)


I checked his papers. This is his home. There was only one caveat, he's supposed to be dead. I've now made him dead. 

![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/644f1ecf-14c0-474a-ba67-2a4b9bf7752b)

**Comment by YggdrasilWotLK** [comment]
Moved to DB

DELETE FROM creature_addon WHERE guid = 121653;
INSERT INTO creature_template_addon (entry, path_id, mount, bytes1, bytes2, emote, visibilityDistanceType, auras)
VALUES 
(31281, 0, 0, 0, 1, 0, 0, "58806");
