### ISSUE TITLE
(QUEST ID 11244) Harpoons not despawning after use/shouldn't be reusable

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#3]
Rescuing the Rescuers

Impaled soldiers can be saved infinetly

I don't think they sticked 8 lances into one soldier, did they?

https://www.wowhead.com/wotlk/quest=11244/rescuing-the-rescuers

Completed quest in quite a weird sadomazo way

**Comment by YggdrasilWotLK** [comment]
Edit: The issue isn't the soldiers, it's the objects not despawning, correct? So we add despawn after loot?

**Comment by SamoyedProtW** [comment]
> Edit: The issue isn't the soldiers, it's the objects not despawning, correct? So we add despawn after loot?

Yeah, either despawn soldier with lance or just lance, otherwise it looks like a weird sadomazo game of put it out and back in for your amusement

**Comment by YggdrasilWotLK** [comment]
Added timer to prevent reuse of the same spear in case the event fails
