### ISSUE TITLE
Mining node in the ground (Icecrown)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#30]
There seems to be mining node stuck in icecrown at 63.84 , 22,74 .
The map shows that an ore should be in that spot, yet none is visible on the surface.

Please move the node up, so it can be minable (or disable it so it doesn't waste space)

![WoWScrnShot_070924_193905](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/957d1ee7-ac0e-4fb2-8adb-f2664d4e08b3)

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/157967573/55bb790e-4e4f-4c4a-88d2-40a43d37c72b)

Sus. Moved
