### ISSUE TITLE
NPC interaction killing quest giver (Winterfin Caverns)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#34]
Inside Winterfin Caverns (Borean Tundra) there is NPC called "Lurgglbr", that is supposed to stay inside of cage and only leave the cage once the player starts escort quest (Escape from the winterfin caverns).

However hostile NPC Winterfin Oracle is patrolin nearby, and when it spots the quest giver inside of cage, it starts attacking him, resulting in the friendly NPC leaving the cage and the death of the quest giver.

![WoWScrnShot_071124_013902](https://github.com/YggdrasilWotLK/Yggdrasil-WoW/assets/74271882/d441783b-a10e-4df6-b54f-4f2b86835537)

The hostile NPC should ignore the quest giver while they're in the cage, however this is not happening.

**Comment by Ye-Old-Potato** [comment]
Unable to replicate this issue - The Oracle as described seems to have no interest in attacking the quest NPC, even with having brought them closer to each other and shadowmelded out of threat. So further information on how to replicate, or investigation will be needed for this one.

**Comment by JaRy66** [comment]
Unfortunately cannot provide how to reproduce, as when I walked in the first time, the oracle just killed him. I waited 5 minutes for the NPC respawn and then he attacked him immediately again.
But also the hostile NPC was standing still during the entire duration of the 5 minutes so probably something was wrong with that specific one

**Comment by YggdrasilWotLK** [comment]
Verified issue stemming from NPC's script not resetting unit flags on death, only on respawn. Needs rescripting of unit flags reset on death too

**Comment by YggdrasilWotLK** [comment]
I just moved the NPC killing the quest giver so that he won't be in aggro range. Probably easier than correcting the flag reset in the core
