### ISSUE TITLE
Ursok the bear god

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#35]
In the middle of the fight Ursok disappears, helper ragepaw respawns immediately at starting point. Also quest is for some reason not available from the questgiver, got it from GM. All prereqs done, also all non repeatable quests in the whole zone are done.

**Comment by Lortz92** [comment]
i've fixed the despawn, also the pre req quests to do in grizzly are:
12292
12293
12294
12295
12299
12307
12300
12302
12308
12310
12220
12219
12247
12246
12248
12250

After all those quests can be taken Urosc the bear god from Hierophant Thayreen
