### ISSUE TITLE
() Screecher Spirits, unable to collect screecher spirits, maybe works 1 out of 10

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#38]
Screecher Spirits, unable to collect screecher spirits, maybe works 1 out of 10

**Comment by Ye-Old-Potato** [comment]
Did you use the kill a screecher, use the quest item to spawn the spirit and interact with or have a chat with the spirit after? This should cause the spirit to be "collected". If you did all of these and it still didn't update your quest log, please provide a bit more insight on how to replicate this so we can look into it.

As I see, those steps seem to work exactly as the quest text says, so we might need a bit more help replicating this issue.

**Comment by YggdrasilWotLK** [comment]
Unable to reproduce and no more input provided from player, closing as invalid
