### ISSUE TITLE
(quest) hour glass for wyrmrest faction , quest is bugged, its dont flag u to pvp. and u can kill your own hour glass with your spells

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#39]
hour glass for wyrmrest faction , quest is bugged, its dont flag u to pvp. and u can kill your own hour glass with your spells

**Comment by Ye-Old-Potato** [comment]
We will need a bit of digging on this one - Multiple iterations through, with horde and ally testing as well cross-faction testing doesn't bug it out. Nothing unusual is replicable yet so we might need a bit more info on how to replicate and the exact events that caused it to happen.

**Comment by YggdrasilWotLK** [comment]
Unable to reproduce and no more input provided from player, closing as invalid
