### ISSUE TITLE
Mechanics Issue: Animal Blood (DEHTA Debuff in Borean Tundra)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#41]
The blood debuff from Borean Tundra.

The murder of an animal causes you to get blood covered which gives you the debuff, that causes Dehta to attack you on sight.
This blood should wash off and create a "pool of blood" fishing school when you jump into water.
This does not happen, jumping into water does nothing.
Tested on various pools across Borean Tundra, checked with the dev server and live both.

Replication: Simply murder an animal and jump into the water, and observe the lack of a result of that action.

**Comment by Ye-Old-Potato** [comment]
Of note, various issues of similar format and regarding this problem have occurred in AC in the past so I attach here the link for reference during debugging.

 https://github.com/azerothcore/azerothcore-wotlk/issues/398

**Comment by YggdrasilWotLK** [comment]
It also sticks to the air if the debuff expires while flying

![image](https://github.com/user-attachments/assets/46f726dc-1a78-4b27-936d-c68d3c745f02)

**Comment by YggdrasilWotLK** [comment]
@Ye-Old-Potato I've made it drop the blood debuff when swimming in Borean Tundra now.

![image](https://github.com/user-attachments/assets/ae01f231-a60e-4f93-9b46-057450777179)

Do we know how this should behave in shallow waters and waters outside of Borean Tundra? Should it e.g. drop a pool of blood even here in the Scalding Pools, or, say, in the Dalaran fountain if someone with the debuff ports to Dalaran?

![image](https://github.com/user-attachments/assets/7f6436d8-6252-46b6-871f-c041aee4effc)

**Comment by Ye-Old-Potato** [comment]
No. Shallow water should NOT have a blood drop. Remember you cannot fish in these waters? That's the test. You should only be able to drop a bloodpool where you can fish. Though some buggy versions I've seen those pools being able to be "fishable", which itself I cannot say for sure but I know for a fact that the bloodpool should only form where submergence of your character is possible and the "swim" state is reached.

**Comment by YggdrasilWotLK** [comment]
ELUNA-d blood spawn in only swimmable waters. And they are indeed fish pools so they should be fishable. Might wanna check if they're also fishable if on land, not sure. EDIT: Confirmed not fishable on land. All good here then

![image](https://github.com/user-attachments/assets/32881125-e51d-44f8-ad76-fa6f214e1902)
