### ISSUE TITLE
Quest: Bring Em back Alive (ID: 11690)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#43]
Quest: Bring Em back Alive (ID: 11690)

You're supposed to grab a bunch of Kodo using a quest item, mount em, run em back to camp and press 2 to "deliver" em, Alive, obviously as described. Which works perfectly fine in some cases, but there is a point in doing this, where due to reasons unknown and by an unknown precise trigger, it becomes impossible to mount any of the injured Kodo lying about. 

Testing indicates this issue pops up in the event where you might either fall into Combat during this quest, it has also happened if you fall into combat during being on the Kodo, in which case, they have provided a 1 spell "stampede" to use for slowing everyone and running away. Using this too, in some instances seems to bug out the Kodo mounting function through quest item.

First theory: Likely the case is that Kodos who are standing are not retrievable, only the lying ones are. (Can't see why that should be the case)

The replication, however, is ambiguous and sporadic, tried doing it on the QA a bit, couldn't reliably replicate it each time so we might need to narrow down the exact trigger. So I am just putting this as a first-action report needing further investigation.

**Comment by YggdrasilWotLK** [comment]
Found the issue. The kodos won't let themselves be controlled in Warsong Slaughterhouse, the beach or the granary. The spell to control them only works in the general Borean Tundra area (ID 3537) and the farm. Jerking them out of the slaughterhouse and into the general area makes them just fine. 

![image](https://github.com/user-attachments/assets/a69be1bd-0d72-41e0-bc4b-f86a66ac67c4)

**Comment by YggdrasilWotLK** [comment]
All kodos should work fine now as long as the rider doesn't purposely go the wrong way with them
