### ISSUE TITLE
Quest: Foolish Endeavors (ID: 11705) (NOT Gamebreaking, LOW PRIO)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#44]
Quest: Foolish Endeavors (ID: 11705)

There are a few janky bits with this quest, though this is LOW priority. It all seems to go normally but some of the dialogue and moves in the roleplay, make no sense based on what it should be. 

Way to replicate: Simply play through the quest, and observe the dialogue and roleplay elements done as a normal, not overgeared player, would and compare to the video attached herein,.

https://www.youtube.com/watch?v=QoiX4YITKWI&ab_channel=Bue
This video shows how it is supposed to be.

**Comment by YggdrasilWotLK** [comment]
@Ye-Old-Potato From the report I assume there's two issues:
1. Cosmetic RP stuff is off
2. Mob behavior is off making suitably geared players have a hard time.

I'm not overly concerned with point 1 at the moment, but for point 2, could you please offer a short description of 2-3 exact changes you recommend when it comes to mob behavior? We can try overriding some of the mob behavior through player events triggered on being in the area ID with the quest

**Comment by Ye-Old-Potato** [comment]
At the very most I would reckon the only feasible change that wouldn't screw with it too much, is to either give the player a slight power buff of sorts like a empowered kings-like all stats + 15 or something on those lines or something that the npc gives em, or else if none else maybe just slightly weaken the mobs say perhaps reduce the number, or general levels of those adds.

Now granted - both of these elements, are simply highly cosmetic level suggestions that would only, at best, serve to ease the player's "difficulty level" given that even at level 75+ it's incredibly challenging and all guides specific to wotlk 3.3.5a state quite clearly that it is of "feasible difficulty" for a level 71, which seems to only be the case if you specifically are a prot paladin. Not even a DK find's it that easy at 71 and that's generally an absurdity.  

So personally, I've recently retried this in a 2 man team with a healer and a prot warrior.... level 70 and 71 respectively. It genuinely works out just fine if you do that... So I'm not sure if we should alter the mobs themselves or just add a comment saying it's "not suitable for solo" or something of that sort, similar to how group quests have a "group quest" tag on em - Just adding that is adequate enough for people to know what to expect and react accordingly.

**Comment by YggdrasilWotLK** [comment]
Let's try to find a way to nerf the mobs

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/e14ba6b1-ee5f-4108-8d36-4c090e96f9d2)
Hm

**Comment by YggdrasilWotLK** [comment]
https://www.youtube.com/watch?v=QoiX4YITKWI

The quest was pretty much like this video from WotLK classic for me just now, I kept my distance and Saurfang soloed just about everything then I helped finish off the big guy. The RP timers are a little off in that Saurfang's intro doesn't fully complete and his outtro isn't there at all (possibly a smart_scripts issue) but I had no issues fighting at level 71. I'm not sure how you guys had issues with this, did you perhaps aggro all the smaller elites?

**Comment by YggdrasilWotLK** [comment]
@Lortz92 I think the timers are smart_scripted through entryorguid 25729 (Shadowstalker Getry, who starts the quest). Could you try extending the timer for the initial roleplay by 15-ish seconds for example, so Saurfang gets to finish? The part before "Rise" needs to be longer. It's probably called through one of the linked events (61)

I think there's a despawn timer somewhere too that should be removed altogether, and we should call despawn on death of creature ID 25618 (Varisu the Flenser) or a very long timer like 10 minutes to prevent mobs from despawning mid-quest. Any chance that is smart_scripted too?

**Comment by Lortz92** [comment]
I tried but i couldn't add or modify any timer. It is a scripted event but i don't know from where. Basically DB side is calling Script9 init and then you can't do anything since every action is in this script i couldn't find anywhere. So i can't control nor the timer, nor the despawn until i find this script9 somewhere.

**Comment by Lortz92** [comment]
never mind, i've been able to find the script and modify timers for everything. Can you check?

**Comment by Ye-Old-Potato** [comment]
This seems all good, and with Saurfang being able to solo the whole thing - the slightly obtuse "non-soloability" problem is also addressed and voided. Roleplay works perfectly too.
