### ISSUE TITLE
Quest: Last Rites (ID: 12019)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#45]
Quest: Last Rites (ID: 12019)

The quest itself works just fine, but once completed - there is a portal that's supposed to take you down from the Naxx-like-floating-ziggeraut thingy, this portal however, does not work or do anything. 

Intended function: Similar to Naxx portals, this thing should send you down to ground level, but it makes sense once just seen. 

Replication: Finish the quest line (4 quests), and try using the portal thing on top after the roleplay, it does nothing.

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/177766ef-ea30-4307-a006-40f90af87875)

This thing?

**Comment by Ye-Old-Potato** [comment]
Yep, that's the one.

**Comment by YggdrasilWotLK** [comment]
The yellow exit teleporters  are now active for some 3 minutes after completing the quest

**Comment by Ye-Old-Potato** [comment]
Yeah, It's active for a bit after the completion of the quest, I did not time it but it seems to be within reason functional for some amount of time after the quest.

**Comment by YggdrasilWotLK** [comment]
Moved to DB 

INSERT INTO areatrigger_teleport (ID, Name, target_map, target_position_x, target_position_y, target_position_z, target_orientation)
VALUES (5338, 'Last Rites Top -> Down', 571, 3800, 3585, 49, 1.1);
DELETE FROM areatrigger_scripts WHERE entry = 5338;
