### ISSUE TITLE
Flight mode

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#47]
In Stormwing if you fly from inside of city into flight master area - you go through textures. 

On one point of the bridge to Menethil's bridge you lose flight form, also when you enter city in flight form - you have a little lag

**Comment by YggdrasilWotLK** [comment]
These aren't really bugs but just feature jank. 

The bridge is a client-side world map object (WMO). Stock clients like the ones we use run sanity checks when crossing WMOs, same as area checks, and attempts to remove your flight form. The server can't see that the client is doing this (WMOs only exist in the client) and can't prevent it unless we use a much more resource intensive reapplication method or make a custom/modded client. The reason for why it happens by the bridge is that all of Stormwind is one big WMO. So for now this is just a side effect of the feature, try to stay close to ground (but at least 3 yards above, as the automatic reapplication is disabled close to ground to permit landing) when crossing WMO boundaries.

As for how you got under the textures flying to the flight master area, this shouldn't really be possible as there's multiple Z-wise overrides, please send screenshots of the path you took

**Comment by YggdrasilWotLK** [comment]
Closed due to no follow-up
