### ISSUE TITLE
QUEST: The chain gun and you (ID: 12457)

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#48]
**Title:** The chain gun and you ID 12457 Dragonblight zone under wintergarde keep

**Issue:** Point of quest is to rescue injured alliance soldiers by covering chain gun fire, however the NPC's that spawn are supposed to be running, instead they are casually walking, making it very difficult to rescue them as they're very fragile.

**Intended functionality:** The NPC's should be running and try to get out as fast as possible.
https://www.wowhead.com/wotlk/quest=12457/the-chain-gun-and-you
https://youtu.be/ojS-FdUKZJ0

**Proof:** 
![WoWScrnShot_072224_122410](https://github.com/user-attachments/assets/a2668f45-58a2-48a4-9209-28887e742655)

**Reproduction steps:** Just start the quest, and call for alliance soldier to come out of hiding.

**Comment by YggdrasilWotLK** [comment]
I've told the NPC to speed up

**Comment by JaRy66** [comment]
Could they also run in the straight line?

**Comment by YggdrasilWotLK** [comment]
That's not how the quest was designed

**Comment by YggdrasilWotLK** [comment]
https://www.youtube.com/watch?v=vhIXARP4K3U In the WotLK classic video you've shared they run in a straight line but in retail WotLK, which we are emulating, their path zig zags
