### ISSUE TITLE
Quest: The Forgotten Tale (ID: 12291) Minor QoL bug

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#49]
**Title:** The Forgotten Tale (ID: 12291) All of this takes place in Dragonblight

**Issue:** You're given murkweed elixir for this quest so you can speek with forgotten souls, however you should be able to mount up under the influence of the elixir. Right now as soon as you mount up, the elixir effect gets removed from the player. (also seems to wear off when player recieves fall damage, i don't know if that's intended though)

https://www.wowhead.com/wotlk/quest=12291/the-forgotten-tale#comments
https://www.wowhead.com/wotlk/item=37570/murkweed-elixir

**Reproduction steps:** Start the quest, go to forgotten shore, and try to mount up, see if the elixir effect wears off

**Comment by YggdrasilWotLK** [comment]
![image](https://github.com/user-attachments/assets/d25cbc21-87a7-435a-bc18-f17410ac247c)

Added a reapplication on channeling. Not sure if we should change environmental damage removal. Does the player have to go back to the quest giver to get a new elixir if it wears off? If so we should probably add an environmental damage failsafe as a QOL thing

**Comment by JaRy66** [comment]
Every time the elixir wears off the player MUST go back to the quest giver for new elixir, as the elixir is being used.

**Comment by YggdrasilWotLK** [comment]
Environmental damage, including fall damage, isn't removing the buff for me, only casting spells does, did the fall damage perhaps trigger some other spell for you?

**Comment by JaRy66** [comment]
maybe it was very delayed from mount, i clicked in on elixir mid air, it kicked me off the mount to drink the elixir, and wore of when I hit the ground. Now that you're saying it it very likely was from the "expiring" mount too
