### ISSUE TITLE
Quest: Zero Tolerance (ID: 12686)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#50]
Quest: Zero Tolerance (ID: 12686) (Zul'Drak)

You're supposed to be able to use a quest-provided stick to convert the undead troll into a minion, said minion must become an elite upon conversion. This minion must also fill out his HP bar upon conversion normally - This doesn't happen and makes the actual elite fight impossible to fully complete with the minion. It does however register without having used the minion entirely, but it still isn't the intended functionality. Check the video below for what it should be doing.

https://www.youtube.com/watch?v=6VyW7VbNDdU&ab_channel=WarcrafterSnorri

Simply pick the quest (Might have to finish the pre-requisite quest line) and try converting a troll target from quest and see what happens.

**Comment by Lortz92** [comment]
I couldn't try if the quest works correctly killing Darmuk with Hand of Drakuru. Can you please provide me the pre req quest? Anyway i've added the spawn health of Hand of Drakuru to 100, so you can test it too!
