### ISSUE TITLE
(NPC) Onslaught Gryphon Rider Flight Pathing Issue

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#59]
Onslaught Harbour, Icecrown. There are these bunch of Gryphon riders that fall into part of a quest but are problematic restrictions to doing a few quest lines in the area. Observe the image below, the problem with them is that their mechanics have a lot of jank, for instance - They swim on their "Flying" gryphons. Second part, They fly about and throw spears at you from a seriously mad range - To the point that you can't even DG them to you. And outside of DKs and range classes, they're basically un-attackable or more like un-reachable. And they do an actually significant degree of damage too, so it would really be impossible to work around these. Refer to the image for a swimming Gryphon.

![image](https://github.com/user-attachments/assets/db3e05ee-c8e3-4d35-8753-0ffce31cad6e)

Here's the IDs for ease of analysis - 
![image](https://github.com/user-attachments/assets/b867de16-0813-403e-bc8b-203884a0b538)

Now normally, they are supposed to throw a spear at you, and move towards you, repeating this process, either that, or are supposed to at least be close enough to the ground that you can stun/silence them in some way just enough to make them possible to engage, presently, they are just a looming threat you realistically can't even run away from due to the sheer number, density and aggro ranges of these things.

There's no express evidence I can find online for exactly how they should behave, I only have my own past experience on playing this part to go off though, so yes that is a caveat, now I personally had no issue ploughing through this - But I do imagine there will eventually be complaints regarding this from someone.

**Comment by YggdrasilWotLK** [comment]
I've had a look:
Pathing: I see that a part of the path around the cathedral island is too low for sure. This doesn't affect all mobs, only 1-2 at a time. I fix.

Combat interaction: As for their spear and Death Grip - their Throw Spear spell is a 40-yard ability so it's correct that they are out of range of most player spells. They're not supposed to move closer to you on throw nor supposed to be in range of stun/silence/other CC. This is how they were designed. Not a bug. The way to handle them is to run out of their range till they come closer to the ground and then hammer them. And, they are supposed to be immune to Death Grip FYI. https://www.wowhead.com/npc=29333/onslaught-gryphon-rider#comments:id=461933

**Comment by Ye-Old-Potato** [comment]
Ah yeah that's fair enough then. Though they are affected by DeathGrip i have tried that and it does work.

I am going to assume the pathing might resolve this part as well. Even if their ranges are large, there's no effective way of getting them to come down, at least I have not yet successfully gotten em to do that without a deathgrip simply because the best bet is to fully escape their aggro range entirely and cause em to return. They have some strange effect definitely, either the hitbox or some kind of Z axis stuff, you can entirely de-aggro them by range, but not bring em to attackable levels.

**Comment by YggdrasilWotLK** [comment]
Fixed the pathing, leaving DG as is. Call it a QoL feature
