### ISSUE TITLE
Quest: Judgment Day Comes!

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#60]
**Title:** Judgment Day Comes! (Quest ID: 13226)

**Issue:** The quest sends you to Highlord Tirion Fordring, and you should talk to him at the Argent Vanguard. However the zone changes already and by the point where I am sent to him, he is no longer there, for me he is in Crusader's Pinnacle, but he won't accept my quest there, so I can't submit the quest.

**Intended functionality:** Considering that Tirion changes his place many times during zone changes,  you should be able to submit the quest to every version of tirion (or at least to all his versions between Argent Vanguard and Crusader's pinnacle)

![WoWScrnShot_080624_220419](https://github.com/user-attachments/assets/300e2b3d-ada2-4af6-9abe-ebe8ba0497ce)

**Comment by YggdrasilWotLK** [comment]
https://www.youtube.com/watch?time_continue=77&v=dc5sBGfz3kE&embeds_referring_euri=https%3A%2F%2Fduckduckgo.com%2F&themeRefresh=1

The various Fordrings you see are all different creatures. We can't add the quest to be handed in at all of them. Nor is the intended hand-in location every version of him, but only the one at Argent Vanguard. I can't reproduce this either (ie. Fordring appears in and accepts my quest just fine in Argent Vanguard) so I think this is just a side effect of the phase reset we did when you got stuck in that tent? We can align your phase again next time you drop by but we're not changing the quest nor the NPC scripts for it
