### ISSUE TITLE
Minor: unusual NPC behavior

### ISSUE THREAD

**Issue by JaRy66** [YggdrasilWotLK/Yggdrasil-WoW#62]
![WoWScrnShot_080724_001820](https://github.com/user-attachments/assets/5174742a-548d-4192-9683-254677c8bb8e)
Onslaught Harbor has probably intruduced some submarine gryphons, looks like the scarlet onslaught have some new breakthrough technology.

On a serious note, please check the pathing of the patroling gryphons in Onslaught Harbor, some NPC's on foot were also under water.

**Comment by YggdrasilWotLK** [comment]
Duplicate, closing re https://github.com/YggdrasilWotLK/Yggdrasil-WoW/issues/59
