### ISSUE TITLE
() Quest Valduran the Stormborn didn't work properly. He starts in a whirlwind-like stance. Using the quest horn called both NPCs and started the fight, but during the encounter you are supposed to be able to fight with them. The game would not let me attack Valduran. Said "Invalid target", I believe. Also, it is supposed to start a dialogue between Valduran and the elites. Valduran killed both elite NPCs, then returned to his whirlwind stasis & regained full health. THEN he started his portion of the dialogue and attacked me, leaving the player to kill him alone without the aid of the elites.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#73]
Quest Valduran the Stormborn didn't work properly. He starts in a whirlwind-like stance. Using the quest horn called both NPCs and started the fight, but during the encounter you are supposed to be able to fight with them. The game would not let me attack Valduran. Said "Invalid target", I believe. Also, it is supposed to start a dialogue between Valduran and the elites. Valduran killed both elite NPCs, then returned to his whirlwind stasis & regained full health. THEN he started his portion of the dialogue and attacked me, leaving the player to kill him alone without the aid of the elites.

**Comment by Ye-Old-Potato** [comment]
This looks good to go.
