### ISSUE TITLE
Reclaiming the Ruins quest can not be completed

### ISSUE THREAD

**Issue by SamoyedProtW** [YggdrasilWotLK/Yggdrasil-WoW#75]
Quest finisher NPC does not accept finished quest. Bug also has been observed by GM Zeleot

**Comment by YggdrasilWotLK** [comment]
Can't reproduce, please elaborate on reproduction steps @SamoyedProtW

**Comment by YggdrasilWotLK** [comment]
Closing for now as we can't reproduce and author not supplying further information
