### ISSUE TITLE
scourgelord tyrannus seems to be bugged, wont start rp.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#8]
scourgelord tyrannus seems to be bugged, wont start rp.

**Comment by YggdrasilWotLK** [comment]
Confirmed, happens on evade. Hard reset flag removed.

**Comment by Ye-Old-Potato** [comment]
This is checked and verified to be functional - Tyrannus now works normally, upon wipes, he reappears as needed, and as long as the prior 2 bosses are done, the Tyrannus script will function normally.
