### ISSUE TITLE
Mob issue (Overseer Faedris) (Creature ID: 32250)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#80]
Mob issue
Multi-spawn. Check Screenshots for exact positions of these guys, I tried killing em and they still seem to want to stop spawning, but the issue persists and I couldn't figure the command to "hakai" them or like delete the spawner or at least I don't know how to use such a command. 

![WoWScrnShot_081724_012309](https://github.com/user-attachments/assets/7a8b9732-ab0f-4802-bf3c-84c05cf465d5)
![WoWScrnShot_081824_105134](https://github.com/user-attachments/assets/0d9d4792-7a20-42ba-804a-40b9241b3752)

**Comment by YggdrasilWotLK** [comment]
I think we might be jumping the gun here if we go straight for the delete button, I'm guessing there's two because they should be phased separately

**Comment by YggdrasilWotLK** [comment]
Update: Thanks for sharing the GUID lows (the 6-digit number of the individual spawns), makes it very quick to follow up the report!

https://www.wowhead.com/wotlk/npc=32250/overseer-faedris#objective-of

He's only related to one quest in phase 1 so I've deleted the one that's not in the tent
