### ISSUE TITLE
Quest: Dark Horizon (QID: 12664)

### ISSUE THREAD

**Issue by Ye-Old-Potato** [YggdrasilWotLK/Yggdrasil-WoW#81]
Quest: Dark Horizon (QID: 12664)

Drakuru gives you this quest, its part of the chain from the unliving choker drop from the undead near the Ebon camp in Zuldrak. 

The item starts a chain that gives you "Ensorcelled Choker" item - This thing turns you into a scourge ghoul (Scourge disguise buff).
 
This aura ID is 51966, however, for the quest Dark Horizons, upon accepting the quest from Drakuru you are supposed to also get a second buff with the ID 52191, this second one doesn't get applied and this causes the quest to be non-completable.

Consult the images below to see one with and one without the buff. As observed on a player, and tested independently, not having this second buff causes you to be unable to take the "tour flight" from the NPC that gives you said flight. That second aura adds onto the player if it isn't already on them, upon accepting the quest from Drakuru, as well as upon interacting with the flight guy that gives you the tour. 

For some reason, this aura is not getting applied by itself if you normally do the quest chain, but it doesn't consistently occur each iteration however 1 player has observed this problem repeat 2 times, and I myself only managed to replicate it in 1 our of 5 iterations. So there is likely some jank in the script with these 2 npcs giving you the aura (ID: 52191).

Consequential problem: Cannot take tour, can talk to npc and select the dialogue, but it does nothing.

![Should](https://github.com/user-attachments/assets/aedd78b5-8a20-4364-bb79-bad678773ef6)
![Not](https://github.com/user-attachments/assets/144b6781-0e1f-4d71-806c-65c3be3ef814)

**Comment by YggdrasilWotLK** [comment]
Investigating 🔎

**Comment by YggdrasilWotLK** [comment]
This works fine for me with two scourge disguise buffs, just one buff and even without any buff (by adjusting my faction to the scourge's) so whatever is causing this is probably not the disguise buffs

**Comment by YggdrasilWotLK** [comment]
Found the cause, it's a range limitation. Try talking to the NPC at max range and it won't cast the gargoyle flight spell. If you're standing very close or on top of him it'll activate just fine. @Lortz92 possible range limitation on the spell cast smart_scripts entry on NPC ID 28666? Or maybe we can somehow reduce the interaction range to match the range required for the spell to cast?

Edit: I've had a look at the smart_scripts for the NPC and there's no range limitation present DB side at least

Edit 2: ELUNA-d the gossip interaction to be interactive regardless of range (as long as on gossip hello is called, of course) and it works OK on dev now. Please test @Ye-Old-Potato  so we can push to live

**Comment by Ye-Old-Potato** [comment]
Yes, this seems to work just fine now - Looks about right and I can't seem to break it by trying funny things.  
I'd say this is pretty much good to go right away.
