### ISSUE TITLE
() quest exorcism in honor hold has many npc

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#88]
quest exorcism in honor hold has many npc

the exorcism of colonel jules - quest name

**Comment by Ye-Old-Potato** [comment]
This as described does happen on our server, however, observation on various sources seems to indicate that this massive number isn't how it's supposed to work. Various video guides of this seem to indicate that you should have a smaller number of spawns, here's an example of this though i can't find a verifyable 3.3.5a video, this looks to be close enough being an actual tbc video.

https://www.youtube.com/watch?v=ZM-S3UPl0H8&ab_channel=Sipder

**Comment by YggdrasilWotLK** [comment]
The adds should be much fewer and have different positioning, plus the friendly NPC isn't supposed to start swimming mid-air if rescued. Looks like we have some rescripting to do. And using the beads to heal the friendly NPC resets it. Let's move it to SAI

![image](https://github.com/user-attachments/assets/d49076a1-c91e-464d-bf59-fe32ac6336c5)

**Comment by YggdrasilWotLK** [comment]
@Lortz92 I see the quest is already SAI with each involved NPC having its own entry, from 22431 (the NPC next to the bed, doing the exorcism), 22432 (the guy floating around being exorcised) and the skull NPCs (22507, they're actually invisible and only turn visible on casting a spell displaying the skull). Would you like to check out the scripts?

**Comment by Lortz92** [comment]
So at the moment the spawn of darkness revelead are controlled by spell 39284. For the moment i made them visible since they were invisible, we need to control those spawns by removing this spell entry and rescript the spawns.

**Comment by YggdrasilWotLK** [comment]
I've reduced the number of mobs, corrected Barada's emote reset on enter/leave combat, and scripted the ceiling hurricane in ELUNA now. Only things left are Jules' hanging emote (he's stiff like a stick mid-air) and the air swimming post-rescue. Might just go live like this as it's functional and work out the rest later

**Comment by YggdrasilWotLK** [comment]
Unjanked most of it, added a respawn reset to ensure the mob doesn't become interactable while mid air etc., please test

**Comment by YggdrasilWotLK** [comment]
Tested, is ok
