### ISSUE TITLE
Sholazar - Swindlegrion's Dig
Ruffian shows up as minced meat until it comes to attack, then morphing  into ruffian form.

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#9]
Sholazar - Swindlegrion's Dig
Ruffian shows up as minced meat until it comes to attack, then morphing  into ruffian form.

**Comment by YggdrasilWotLK** [comment]
Issue is related to UH DK corpse explosion, model sticking for some reason. Researching

**Comment by Lortz92** [comment]
I've checked that just 1 NPC is bugged, i can think of removing him. I don't know if they will respawn with bugged display, i also tried to change it but nothing but it still bugs out. What do you think?

**Comment by YggdrasilWotLK** [comment]
Don't remove him, it's our troubleshooting specimen he he

So far we've only found one NPC with this issue but it stems from a larger problem: Unholy DK corpse explosions trigger a hidden debuff (ID 51270) that applies various exploded corpse display IDs (https://www.wowhead.com/wotlk/spell=51328/corpse-explosion). 

This aura should, and is, removed on despawn. But, a few seconds after respawn, it is somehow applied again. 

I'm looking into ways to fix...

![image](https://github.com/user-attachments/assets/8156640f-5cc8-4f30-8e6f-aeb72d30c7cc)

**Comment by YggdrasilWotLK** [comment]
Turns out it becomes permanent if corpse explosion hits a target during its respawn grace period (ie. between the time it spawns into the world, at which point it is dead, and its NPC flags, HP, and visibility are restored). 

The right fix is probably to make them immune all to spells/damage during this grace period, including aura ID 51270, but for now I've just set up corpse explosion to wear off after 2 minutes in the event that targets don't despawn.

**Comment by YggdrasilWotLK** [comment]
Turns out I was wrong, my script can't hook onto this NPC because it casts spell ID 51270 on itself every time it enters and leaves combat (as opposed to being cast by a player), being the only guid of template ID 28124 to do so. I'm not sure how to reproduce NPCs casting spells they haven't access to on themselves so I've just replaced the NPC with another guid now
