### ISSUE TITLE
ICC pipe flesh reapers are wall hacking

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#90]
**Title:** Remember to enter the category in the title, such as (QUEST), (NPC), etc.

**Issue:** Please explain what is happening.
The flesh reapers on the pipes between the plague potatoes zap through the wall and come out flying in the other end as they walk from the edges towards the center
![image](https://github.com/user-attachments/assets/f86e05ae-d3dc-43c6-9b87-86477be771c9)

**Intended functionality:** How is the current functionality different from the intended functionality:
They shouldn't wall hack

**Proof:** Please reference original sources for the intended functionality, such as WoW-Head, Elitist Jerks, other WotLK 3.3.5a sources (where not available, WotLK classic data may be considered too)
Wall hacking is illegal

**Reproduction steps:** If not evident from above, please explain how you found the issue. 
Watch them wall hack in literally any ICC

**Comment by YggdrasilWotLK** [comment]
@Lortz92  probably a SAI/waypoint error in DB, could you have a look please?

**Comment by Lortz92** [comment]
Unluckily, they are cpp scripted the ones on pipelines. The only ones that have waypoints setted are the ground ones. Script is: icecrown_citadel.cpp

**Comment by YggdrasilWotLK** [comment]
Pushed a cpp fix PR to AzerothCore, waiting for it to get accepted so we can pull it back

**Comment by YggdrasilWotLK** [comment]
@Lortz92 should we just diff this one? Been 3 weeks

**Comment by YggdrasilWotLK** [comment]
Diffing this one from next compile
