### ISSUE TITLE
Death Comes From On High - Can't leave vehicle/controlled NPC

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#91]
Upon completion of death knight beginner quest Death Comes From On High, I could not dismiss the Eye of Acherus as intended. The X button in the action tray did nothing and I had to relog to get rid of the Eye.

**Comment by YggdrasilWotLK** [comment]
@Ye-Old-Potato could you please try confirming the report?

**Comment by Ye-Old-Potato** [comment]
Yep, I'll look into it today as soon as I am able. I have, however, done this dismissal successfully about 2 times in the past on the live server, about 2 months ago or so. I'll reverify its current condition and update.

**Comment by Ye-Old-Potato** [comment]
Current observation indicates that the eye mostly works, cancellation and all its "mission critical" functions work perfectly fine. What doesn't work is such things as the "Attack", "Summon Ghouls", "Return to base" abilities. The Shroud also seems ambiguous in its efficacy, however, it appears to mostly be in line with other sources from Blizzard functionality in 3.3.5a. I have a video recorded of this however it is too large to upload here, so i'll have it available as and when required.. However specific to this concern raised here, there exist 2 different "X" buttons - One of which does exactly what its supposed to while the other is a dud. The one that cancels channeling and returns you to your character works, however, the one that returns the eye back to home without canceling, does absolutely nothing.

Long and short of it, all mission-critical functions are perfectly functional, with a few more cosmetic or aesthetic elements dysfunctional.

**Comment by YggdrasilWotLK** [comment]
Both buttons work and are lived now
