### ISSUE TITLE
Proto-Drake Riders in Utgarde Keep only start pathing after leaving combat

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#94]
NPC ID 24849, the five dragons in table creatures with movementType = 2 should be pathing all the time but only assume pathing after leaving combat. @Lortz92 maybe some smart_script jank?

**Comment by Lortz92** [comment]
I fixed this issue, was an entry in smart_script that i deleted.
