### ISSUE TITLE
Dark Iron mobs at Ironband's Compound should have wander distance

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#96]
Most currently don't.

Issue may affect the nearby Rockjaw Ambushers and Bonesnappers in Helm's Bed Lake too.

@Lortz92  would you like to look at this? Probably a flat 5 yards idle movement or so in the Dark Iron Spies' creature table entries

WoW classic reference, ca. 05:20: https://www.youtube.com/watch?v=8rmtWSZhtYw

**Comment by Lortz92** [comment]
I made them all move randomly so no one will stand still .
