### ISSUE TITLE
Icecrown sharks don't have movement

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#98]
They currently just stand in place. NPC ID 29392. Here's an ELUNA hack but it's probably best to give these DB entry movement:

local function FixSharkPath(event, creature)
	creature:NearTeleport(creature:GetX(),creature:GetY(),creature:GetZ()-5,creature:GetO())
	creature:MoveRandom(20)
end

RegisterCreatureEvent(29392, 5, FixSharkPath)

**Comment by Lortz92** [comment]
Fixed movement of sharks too, script can be detached.
