### ISSUE TITLE
Obsidian Sanctum mobs don't patrol along their waypaths but instead just wander within a wanderdistance

### ISSUE THREAD

**Issue by YggdrasilWotLK** [YggdrasilWotLK/Yggdrasil-WoW#99]
They should patrol

https://www.youtube.com/watch?v=LR7TYiUmTv0

**Comment by YggdrasilWotLK** [comment]
@Ye-Old-Potato the big guys and the packs in the back are now pathed, please have a look and let us know if we should correct/improve anything

**Comment by Ye-Old-Potato** [comment]
Yes, Can confirm that these mobs and their pathing seems to now be much more normal - However, on certain off cases, for no explicable reasons there are instances where they forget their path and basically "get lost like misguided puppies" if you will. 

This peculiarity seems to be more frequent in the 25man difficulty as opposed to the 10. 

Observe screenshot below for reference to one example. 
These guys did 2 rounds normally before this was taken, then started lagging behind, shortly before fixing themselves again. 

![image](https://github.com/user-attachments/assets/5995d6a0-4d49-463b-aa9d-4881d705047f)

If such a status is deemed acceptable, which to me, seems acceptable given the limited few off cases and being 90% normally apparent, I would recommend overlooking those few edge-cases, and in such case, this is good to go live as in its current state.

**Comment by YggdrasilWotLK** [comment]
Added extra points around start and end to align lost puppies. No more lost puppies
